
// var dataJson = {
//     "status": 1,
//     "code": "0000",
//     "mess": "Lấy số liệu báo cáo thành công",
//     "data": {
//         "data": [
//             {
//                 "nam": 2020,
//                 "thang": 4,
//                 "id_tinh": 2,
//                 "ten_tinh": "An Giang",
//                 "ten_quan": null,
//                 "thang_kehoach": "      16,949.99",
//                 "thang_luyke_thuchien": "      13,356.89",
//                 "thang_phantram_th": "          78.80",
//                 "quy_kehoach": "      50,252.96",
//                 "quy_luyke_thuchien": "      13,356.89",
//                 "quy_phantram_th": "          26.58",
//                 "nam_kehoach": "     201,680.57",
//                 "nam_luyke_thuchien": "      63,071.35",
//                 "nam_phantram_th": "          31.27",
//                 "tb_thang_hientai": "         445.25",
//                 "tb_thang_truoc": "         528.71",
//                 "ss_bq_tocdo_tang": "         -15.79",
//                 "tb_thang_hientai_1": "         445.25",
//                 "tb_ngay_cungky": "         528.71",
//                 "ss_bq_tocdo_tang_ngaycungky": "         -15.79",
//                 "tb_thang_hientai_2": "         445.25",
//                 "tb_thang_cungky": "         519.16",
//                 "ss_bq_tocdo_tang_thangcungky": "         -14.24",
//                 "tb_lk_ngay_nam_n": "         521.27",
//                 "tb_lk_ngay_nam_n_1": "         421.01",
//                 "ss_bq_tdt_lkengay_2nam": "          23.81",
//                 "tb_ngay_nam_n": "         521.27",
//                 "tb_ngay_nam_n_1": "         512.98",
//                 "ss_bq_tdt_2nam": "           1.62",
//                 "d1": 13357,
//                 "d2": 0,
//                 "d3": 0,
//                 "d4": 0,
//                 "d5": 0,
//                 "d6": 0,
//                 "d7": 0,
//                 "d8": 0,
//                 "d9": 0,
//                 "d10": 0,
//                 "d11": 0,
//                 "d12": 0,
//                 "d13": 0,
//                 "d14": 0,
//                 "d15": 0,
//                 "d16": 0,
//                 "d17": 0,
//                 "d18": 0,
//                 "d19": 0,
//                 "d20": 0,
//                 "d21": 0,
//                 "d22": 0,
//                 "d23": 0,
//                 "d24": 0,
//                 "d25": 0,
//                 "d26": 0,
//                 "d27": 0,
//                 "d28": 0,
//                 "d29": 0,
//                 "d30": 0,
//                 "d31": 0
//             },
//             {
//                 "nam": 2020,
//                 "thang": 4,
//                 "id_tinh": 178,
//                 "ten_tinh": "Bạc Liêu",
//                 "ten_quan": null,
//                 "thang_kehoach": "       3,985.80",
//                 "thang_luyke_thuchien": "       3,718.42",
//                 "thang_phantram_th": "          93.29",
//                 "quy_kehoach": "      11,817.00",
//                 "quy_luyke_thuchien": "       3,718.42",
//                 "quy_phantram_th": "          31.47",
//                 "nam_kehoach": "      49,051.48",
//                 "nam_luyke_thuchien": "      17,713.55",
//                 "nam_phantram_th": "          36.11",
//                 "tb_thang_hientai": "         123.95",
//                 "tb_thang_truoc": "         146.22",
//                 "ss_bq_tocdo_tang": "         -15.23",
//                 "tb_thang_hientai_1": "         123.95",
//                 "tb_ngay_cungky": "         146.22",
//                 "ss_bq_tocdo_tang_ngaycungky": "         -15.23",
//                 "tb_thang_hientai_2": "         123.95",
//                 "tb_thang_cungky": "         131.18",
//                 "ss_bq_tocdo_tang_thangcungky": "          -5.51",
//                 "tb_lk_ngay_nam_n": "         146.40",
//                 "tb_lk_ngay_nam_n_1": "         104.56",
//                 "ss_bq_tdt_lkengay_2nam": "          40.02",
//                 "tb_ngay_nam_n": "         146.40",
//                 "tb_ngay_nam_n_1": "         124.55",
//                 "ss_bq_tdt_2nam": "          17.54",
//                 "d1": 3718,
//                 "d2": 0,
//                 "d3": 0,
//                 "d4": 0,
//                 "d5": 0,
//                 "d6": 0,
//                 "d7": 0,
//                 "d8": 0,
//                 "d9": 0,
//                 "d10": 0,
//                 "d11": 0,
//                 "d12": 0,
//                 "d13": 0,
//                 "d14": 0,
//                 "d15": 0,
//                 "d16": 0,
//                 "d17": 0,
//                 "d18": 0,
//                 "d19": 0,
//                 "d20": 0,
//                 "d21": 0,
//                 "d22": 0,
//                 "d23": 0,
//                 "d24": 0,
//                 "d25": 0,
//                 "d26": 0,
//                 "d27": 0,
//                 "d28": 0,
//                 "d29": 0,
//                 "d30": 0,
//                 "d31": 0
//             },
//             {
//                 "nam": 2020,
//                 "thang": 4,
//                 "id_tinh": 272,
//                 "ten_tinh": "Bến Tre",
//                 "ten_quan": null,
//                 "thang_kehoach": "      12,587.82",
//                 "thang_luyke_thuchien": "      10,795.27",
//                 "thang_phantram_th": "          85.76",
//                 "quy_kehoach": "      37,320.09",
//                 "quy_luyke_thuchien": "      10,795.27",
//                 "quy_phantram_th": "          28.93",
//                 "nam_kehoach": "     152,091.92",
//                 "nam_luyke_thuchien": "      49,993.12",
//                 "nam_phantram_th": "          32.87",
//                 "tb_thang_hientai": "         359.85",
//                 "tb_thang_truoc": "         391.37",
//                 "ss_bq_tocdo_tang": "          -8.05",
//                 "tb_thang_hientai_1": "         359.85",
//                 "tb_ngay_cungky": "         391.37",
//                 "ss_bq_tocdo_tang_ngaycungky": "          -8.05",
//                 "tb_thang_hientai_2": "         359.85",
//                 "tb_thang_cungky": "         393.60",
//                 "ss_bq_tocdo_tang_thangcungky": "          -8.57",
//                 "tb_lk_ngay_nam_n": "         413.17",
//                 "tb_lk_ngay_nam_n_1": "         317.46",
//                 "ss_bq_tdt_lkengay_2nam": "          30.15",
//                 "tb_ngay_nam_n": "         413.17",
//                 "tb_ngay_nam_n_1": "         391.51",
//                 "ss_bq_tdt_2nam": "           5.53",
//                 "d1": 10795,
//                 "d2": 0,
//                 "d3": 0,
//                 "d4": 0,
//                 "d5": 0,
//                 "d6": 0,
//                 "d7": 0,
//                 "d8": 0,
//                 "d9": 0,
//                 "d10": 0,
//                 "d11": 0,
//                 "d12": 0,
//                 "d13": 0,
//                 "d14": 0,
//                 "d15": 0,
//                 "d16": 0,
//                 "d17": 0,
//                 "d18": 0,
//                 "d19": 0,
//                 "d20": 0,
//                 "d21": 0,
//                 "d22": 0,
//                 "d23": 0,
//                 "d24": 0,
//                 "d25": 0,
//                 "d26": 0,
//                 "d27": 0,
//                 "d28": 0,
//                 "d29": 0,
//                 "d30": 0,
//                 "d31": 0
//             },
//             {
//                 "nam": 2020,
//                 "thang": 4,
//                 "id_tinh": 483,
//                 "ten_tinh": "Cà Mau",
//                 "ten_quan": null,
//                 "thang_kehoach": "       3,741.66",
//                 "thang_luyke_thuchien": "       3,373.77",
//                 "thang_phantram_th": "          90.17",
//                 "quy_kehoach": "      11,093.20",
//                 "quy_luyke_thuchien": "       3,373.77",
//                 "quy_phantram_th": "          30.41",
//                 "nam_kehoach": "      45,387.10",
//                 "nam_luyke_thuchien": "      16,612.04",
//                 "nam_phantram_th": "          36.60",
//                 "tb_thang_hientai": "         112.46",
//                 "tb_thang_truoc": "         161.76",
//                 "ss_bq_tocdo_tang": "         -30.48",
//                 "tb_thang_hientai_1": "         112.46",
//                 "tb_ngay_cungky": "         161.76",
//                 "ss_bq_tocdo_tang_ngaycungky": "         -30.48",
//                 "tb_thang_hientai_2": "         112.46",
//                 "tb_thang_cungky": "         114.90",
//                 "ss_bq_tocdo_tang_thangcungky": "          -2.12",
//                 "tb_lk_ngay_nam_n": "         137.30",
//                 "tb_lk_ngay_nam_n_1": "          89.00",
//                 "ss_bq_tdt_lkengay_2nam": "          54.27",
//                 "tb_ngay_nam_n": "         137.30",
//                 "tb_ngay_nam_n_1": "         115.44",
//                 "ss_bq_tdt_2nam": "          18.94",
//                 "d1": 3374,
//                 "d2": 0,
//                 "d3": 0,
//                 "d4": 0,
//                 "d5": 0,
//                 "d6": 0,
//                 "d7": 0,
//                 "d8": 0,
//                 "d9": 0,
//                 "d10": 0,
//                 "d11": 0,
//                 "d12": 0,
//                 "d13": 0,
//                 "d14": 0,
//                 "d15": 0,
//                 "d16": 0,
//                 "d17": 0,
//                 "d18": 0,
//                 "d19": 0,
//                 "d20": 0,
//                 "d21": 0,
//                 "d22": 0,
//                 "d23": 0,
//                 "d24": 0,
//                 "d25": 0,
//                 "d26": 0,
//                 "d27": 0,
//                 "d28": 0,
//                 "d29": 0,
//                 "d30": 0,
//                 "d31": 0
//             },
//             {
//                 "nam": 2020,
//                 "thang": 4,
//                 "id_tinh": 614,
//                 "ten_tinh": "Cần Thơ",
//                 "ten_quan": null,
//                 "thang_kehoach": "      44,549.22",
//                 "thang_luyke_thuchien": "      32,742.33",
//                 "thang_phantram_th": "          73.50",
//                 "quy_kehoach": "     132,078.54",
//                 "quy_luyke_thuchien": "      32,742.33",
//                 "quy_phantram_th": "          24.79",
//                 "nam_kehoach": "     524,536.17",
//                 "nam_luyke_thuchien": "     155,796.56",
//                 "nam_phantram_th": "          29.70",
//                 "tb_thang_hientai": "       1,091.40",
//                 "tb_thang_truoc": "       1,322.52",
//                 "ss_bq_tocdo_tang": "         -17.48",
//                 "tb_thang_hientai_1": "       1,091.40",
//                 "tb_ngay_cungky": "       1,322.52",
//                 "ss_bq_tocdo_tang_ngaycungky": "         -17.48",
//                 "tb_thang_hientai_2": "       1,091.40",
//                 "tb_thang_cungky": "       1,343.01",
//                 "ss_bq_tocdo_tang_thangcungky": "         -18.73",
//                 "tb_lk_ngay_nam_n": "       1,287.58",
//                 "tb_lk_ngay_nam_n_1": "       1,044.73",
//                 "ss_bq_tdt_lkengay_2nam": "          23.25",
//                 "tb_ngay_nam_n": "       1,287.58",
//                 "tb_ngay_nam_n_1": "       1,341.35",
//                 "ss_bq_tdt_2nam": "          -4.01",
//                 "d1": 32742,
//                 "d2": 0,
//                 "d3": 0,
//                 "d4": 0,
//                 "d5": 0,
//                 "d6": 0,
//                 "d7": 0,
//                 "d8": 0,
//                 "d9": 0,
//                 "d10": 0,
//                 "d11": 0,
//                 "d12": 0,
//                 "d13": 0,
//                 "d14": 0,
//                 "d15": 0,
//                 "d16": 0,
//                 "d17": 0,
//                 "d18": 0,
//                 "d19": 0,
//                 "d20": 0,
//                 "d21": 0,
//                 "d22": 0,
//                 "d23": 0,
//                 "d24": 0,
//                 "d25": 0,
//                 "d26": 0,
//                 "d27": 0,
//                 "d28": 0,
//                 "d29": 0,
//                 "d30": 0,
//                 "d31": 0
//             },
//             {
//                 "nam": 2020,
//                 "thang": 4,
//                 "id_tinh": 894,
//                 "ten_tinh": "Hậu Giang",
//                 "ten_quan": null,
//                 "thang_kehoach": "      19,913.95",
//                 "thang_luyke_thuchien": "      17,847.92",
//                 "thang_phantram_th": "          89.63",
//                 "quy_kehoach": "      59,040.45",
//                 "quy_luyke_thuchien": "      17,847.92",
//                 "quy_phantram_th": "          30.23",
//                 "nam_kehoach": "     238,646.02",
//                 "nam_luyke_thuchien": "      79,215.73",
//                 "nam_phantram_th": "          33.19",
//                 "tb_thang_hientai": "         594.93",
//                 "tb_thang_truoc": "         661.83",
//                 "ss_bq_tocdo_tang": "         -10.11",
//                 "tb_thang_hientai_1": "         594.93",
//                 "tb_ngay_cungky": "         661.83",
//                 "ss_bq_tocdo_tang_ngaycungky": "         -10.11",
//                 "tb_thang_hientai_2": "         594.93",
//                 "tb_thang_cungky": "         615.81",
//                 "ss_bq_tocdo_tang_thangcungky": "          -3.39",
//                 "tb_lk_ngay_nam_n": "         654.67",
//                 "tb_lk_ngay_nam_n_1": "         489.75",
//                 "ss_bq_tdt_lkengay_2nam": "          33.67",
//                 "tb_ngay_nam_n": "         654.67",
//                 "tb_ngay_nam_n_1": "         610.29",
//                 "ss_bq_tdt_2nam": "           7.27",
//                 "d1": 17848,
//                 "d2": 0,
//                 "d3": 0,
//                 "d4": 0,
//                 "d5": 0,
//                 "d6": 0,
//                 "d7": 0,
//                 "d8": 0,
//                 "d9": 0,
//                 "d10": 0,
//                 "d11": 0,
//                 "d12": 0,
//                 "d13": 0,
//                 "d14": 0,
//                 "d15": 0,
//                 "d16": 0,
//                 "d17": 0,
//                 "d18": 0,
//                 "d19": 0,
//                 "d20": 0,
//                 "d21": 0,
//                 "d22": 0,
//                 "d23": 0,
//                 "d24": 0,
//                 "d25": 0,
//                 "d26": 0,
//                 "d27": 0,
//                 "d28": 0,
//                 "d29": 0,
//                 "d30": 0,
//                 "d31": 0
//             },
//             {
//                 "nam": 2020,
//                 "thang": 4,
//                 "id_tinh": 985,
//                 "ten_tinh": "Kiên Giang",
//                 "ten_quan": null,
//                 "thang_kehoach": "      19,661.44",
//                 "thang_luyke_thuchien": "      15,641.77",
//                 "thang_phantram_th": "          79.56",
//                 "quy_kehoach": "      58,291.80",
//                 "quy_luyke_thuchien": "      15,641.77",
//                 "quy_phantram_th": "          26.83",
//                 "nam_kehoach": "     233,969.35",
//                 "nam_luyke_thuchien": "      73,308.63",
//                 "nam_phantram_th": "          31.33",
//                 "tb_thang_hientai": "         521.38",
//                 "tb_thang_truoc": "         612.24",
//                 "ss_bq_tocdo_tang": "         -14.84",
//                 "tb_thang_hientai_1": "         521.38",
//                 "tb_ngay_cungky": "         612.24",
//                 "ss_bq_tocdo_tang_ngaycungky": "         -14.84",
//                 "tb_thang_hientai_2": "         521.38",
//                 "tb_thang_cungky": "         598.23",
//                 "ss_bq_tocdo_tang_thangcungky": "         -12.85",
//                 "tb_lk_ngay_nam_n": "         605.85",
//                 "tb_lk_ngay_nam_n_1": "         459.57",
//                 "ss_bq_tdt_lkengay_2nam": "          31.83",
//                 "tb_ngay_nam_n": "         605.85",
//                 "tb_ngay_nam_n_1": "         600.18",
//                 "ss_bq_tdt_2nam": "           0.94",
//                 "d1": 15642,
//                 "d2": 0,
//                 "d3": 0,
//                 "d4": 0,
//                 "d5": 0,
//                 "d6": 0,
//                 "d7": 0,
//                 "d8": 0,
//                 "d9": 0,
//                 "d10": 0,
//                 "d11": 0,
//                 "d12": 0,
//                 "d13": 0,
//                 "d14": 0,
//                 "d15": 0,
//                 "d16": 0,
//                 "d17": 0,
//                 "d18": 0,
//                 "d19": 0,
//                 "d20": 0,
//                 "d21": 0,
//                 "d22": 0,
//                 "d23": 0,
//                 "d24": 0,
//                 "d25": 0,
//                 "d26": 0,
//                 "d27": 0,
//                 "d28": 0,
//                 "d29": 0,
//                 "d30": 0,
//                 "d31": 0
//             },
//             {
//                 "nam": 2020,
//                 "thang": 4,
//                 "id_tinh": 1160,
//                 "ten_tinh": "Sóc Trăng",
//                 "ten_quan": null,
//                 "thang_kehoach": "      10,865.42",
//                 "thang_luyke_thuchien": "       8,880.09",
//                 "thang_phantram_th": "          81.73",
//                 "quy_kehoach": "      32,213.57",
//                 "quy_luyke_thuchien": "       8,880.09",
//                 "quy_phantram_th": "          27.57",
//                 "nam_kehoach": "     130,433.93",
//                 "nam_luyke_thuchien": "      43,565.14",
//                 "nam_phantram_th": "          33.40",
//                 "tb_thang_hientai": "         296.00",
//                 "tb_thang_truoc": "         392.60",
//                 "ss_bq_tocdo_tang": "         -24.61",
//                 "tb_thang_hientai_1": "         296.00",
//                 "tb_ngay_cungky": "         392.60",
//                 "ss_bq_tocdo_tang_ngaycungky": "         -24.61",
//                 "tb_thang_hientai_2": "         296.00",
//                 "tb_thang_cungky": "         357.90",
//                 "ss_bq_tocdo_tang_thangcungky": "         -17.30",
//                 "tb_lk_ngay_nam_n": "         360.05",
//                 "tb_lk_ngay_nam_n_1": "         273.91",
//                 "ss_bq_tdt_lkengay_2nam": "          31.45",
//                 "tb_ngay_nam_n": "         360.05",
//                 "tb_ngay_nam_n_1": "         336.98",
//                 "ss_bq_tdt_2nam": "           6.85",
//                 "d1": 8880,
//                 "d2": 0,
//                 "d3": 0,
//                 "d4": 0,
//                 "d5": 0,
//                 "d6": 0,
//                 "d7": 0,
//                 "d8": 0,
//                 "d9": 0,
//                 "d10": 0,
//                 "d11": 0,
//                 "d12": 0,
//                 "d13": 0,
//                 "d14": 0,
//                 "d15": 0,
//                 "d16": 0,
//                 "d17": 0,
//                 "d18": 0,
//                 "d19": 0,
//                 "d20": 0,
//                 "d21": 0,
//                 "d22": 0,
//                 "d23": 0,
//                 "d24": 0,
//                 "d25": 0,
//                 "d26": 0,
//                 "d27": 0,
//                 "d28": 0,
//                 "d29": 0,
//                 "d30": 0,
//                 "d31": 0
//             },
//             {
//                 "nam": 2020,
//                 "thang": 4,
//                 "id_tinh": 1307,
//                 "ten_tinh": "Tiền Giang",
//                 "ten_quan": null,
//                 "thang_kehoach": "      30,950.04",
//                 "thang_luyke_thuchien": "      25,259.57",
//                 "thang_phantram_th": "          81.61",
//                 "quy_kehoach": "      91,759.99",
//                 "quy_luyke_thuchien": "      25,259.57",
//                 "quy_phantram_th": "          27.53",
//                 "nam_kehoach": "     369,246.67",
//                 "nam_luyke_thuchien": "     117,596.95",
//                 "nam_phantram_th": "          31.85",
//                 "tb_thang_hientai": "         842.00",
//                 "tb_thang_truoc": "         983.86",
//                 "ss_bq_tocdo_tang": "         -14.42",
//                 "tb_thang_hientai_1": "         842.00",
//                 "tb_ngay_cungky": "         983.86",
//                 "ss_bq_tocdo_tang_ngaycungky": "         -14.42",
//                 "tb_thang_hientai_2": "         842.00",
//                 "tb_thang_cungky": "         965.47",
//                 "ss_bq_tocdo_tang_thangcungky": "         -12.79",
//                 "tb_lk_ngay_nam_n": "         971.87",
//                 "tb_lk_ngay_nam_n_1": "         748.19",
//                 "ss_bq_tdt_lkengay_2nam": "          29.90",
//                 "tb_ngay_nam_n": "         971.87",
//                 "tb_ngay_nam_n_1": "         946.57",
//                 "ss_bq_tdt_2nam": "           2.67",
//                 "d1": 25260,
//                 "d2": 0,
//                 "d3": 0,
//                 "d4": 0,
//                 "d5": 0,
//                 "d6": 0,
//                 "d7": 0,
//                 "d8": 0,
//                 "d9": 0,
//                 "d10": 0,
//                 "d11": 0,
//                 "d12": 0,
//                 "d13": 0,
//                 "d14": 0,
//                 "d15": 0,
//                 "d16": 0,
//                 "d17": 0,
//                 "d18": 0,
//                 "d19": 0,
//                 "d20": 0,
//                 "d21": 0,
//                 "d22": 0,
//                 "d23": 0,
//                 "d24": 0,
//                 "d25": 0,
//                 "d26": 0,
//                 "d27": 0,
//                 "d28": 0,
//                 "d29": 0,
//                 "d30": 0,
//                 "d31": 0
//             },
//             {
//                 "nam": 2020,
//                 "thang": 4,
//                 "id_tinh": 1500,
//                 "ten_tinh": "Trà Vinh",
//                 "ten_quan": null,
//                 "thang_kehoach": "       9,798.01",
//                 "thang_luyke_thuchien": "       8,274.19",
//                 "thang_phantram_th": "          84.45",
//                 "quy_kehoach": "      29,048.92",
//                 "quy_luyke_thuchien": "       8,274.19",
//                 "quy_phantram_th": "          28.48",
//                 "nam_kehoach": "     116,785.92",
//                 "nam_luyke_thuchien": "      37,660.01",
//                 "nam_phantram_th": "          32.25",
//                 "tb_thang_hientai": "         275.82",
//                 "tb_thang_truoc": "         319.90",
//                 "ss_bq_tocdo_tang": "         -13.78",
//                 "tb_thang_hientai_1": "         275.82",
//                 "tb_ngay_cungky": "         319.90",
//                 "ss_bq_tocdo_tang_ngaycungky": "         -13.78",
//                 "tb_thang_hientai_2": "         275.82",
//                 "tb_thang_cungky": "         321.18",
//                 "ss_bq_tocdo_tang_thangcungky": "         -14.12",
//                 "tb_lk_ngay_nam_n": "         311.23",
//                 "tb_lk_ngay_nam_n_1": "         228.61",
//                 "ss_bq_tdt_lkengay_2nam": "          36.14",
//                 "tb_ngay_nam_n": "         311.23",
//                 "tb_ngay_nam_n_1": "         298.45",
//                 "ss_bq_tdt_2nam": "           4.28",
//                 "d1": 8274,
//                 "d2": 0,
//                 "d3": 0,
//                 "d4": 0,
//                 "d5": 0,
//                 "d6": 0,
//                 "d7": 0,
//                 "d8": 0,
//                 "d9": 0,
//                 "d10": 0,
//                 "d11": 0,
//                 "d12": 0,
//                 "d13": 0,
//                 "d14": 0,
//                 "d15": 0,
//                 "d16": 0,
//                 "d17": 0,
//                 "d18": 0,
//                 "d19": 0,
//                 "d20": 0,
//                 "d21": 0,
//                 "d22": 0,
//                 "d23": 0,
//                 "d24": 0,
//                 "d25": 0,
//                 "d26": 0,
//                 "d27": 0,
//                 "d28": 0,
//                 "d29": 0,
//                 "d30": 0,
//                 "d31": 0
//             },
//             {
//                 "nam": 2020,
//                 "thang": 4,
//                 "id_tinh": 1616,
//                 "ten_tinh": "Vĩnh Long",
//                 "ten_quan": null,
//                 "thang_kehoach": "      30,730.53",
//                 "thang_luyke_thuchien": "      25,888.48",
//                 "thang_phantram_th": "          84.24",
//                 "quy_kehoach": "      91,109.19",
//                 "quy_luyke_thuchien": "      25,888.48",
//                 "quy_phantram_th": "          28.41",
//                 "nam_kehoach": "     366,273.14",
//                 "nam_luyke_thuchien": "     117,866.94",
//                 "nam_phantram_th": "          32.18",
//                 "tb_thang_hientai": "         862.95",
//                 "tb_thang_truoc": "         997.88",
//                 "ss_bq_tocdo_tang": "         -13.52",
//                 "tb_thang_hientai_1": "         862.95",
//                 "tb_ngay_cungky": "         997.88",
//                 "ss_bq_tocdo_tang_ngaycungky": "         -13.52",
//                 "tb_thang_hientai_2": "         862.95",
//                 "tb_thang_cungky": "         943.45",
//                 "ss_bq_tocdo_tang_thangcungky": "          -8.53",
//                 "tb_lk_ngay_nam_n": "         974.10",
//                 "tb_lk_ngay_nam_n_1": "         742.62",
//                 "ss_bq_tdt_lkengay_2nam": "          31.17",
//                 "tb_ngay_nam_n": "         974.10",
//                 "tb_ngay_nam_n_1": "         935.00",
//                 "ss_bq_tdt_2nam": "           4.18",
//                 "d1": 25888,
//                 "d2": 0,
//                 "d3": 0,
//                 "d4": 0,
//                 "d5": 0,
//                 "d6": 0,
//                 "d7": 0,
//                 "d8": 0,
//                 "d9": 0,
//                 "d10": 0,
//                 "d11": 0,
//                 "d12": 0,
//                 "d13": 0,
//                 "d14": 0,
//                 "d15": 0,
//                 "d16": 0,
//                 "d17": 0,
//                 "d18": 0,
//                 "d19": 0,
//                 "d20": 0,
//                 "d21": 0,
//                 "d22": 0,
//                 "d23": 0,
//                 "d24": 0,
//                 "d25": 0,
//                 "d26": 0,
//                 "d27": 0,
//                 "d28": 0,
//                 "d29": 0,
//                 "d30": 0,
//                 "d31": 0
//             },
//             {
//                 "nam": 2020,
//                 "thang": 4,
//                 "id_tinh": 735,
//                 "ten_tinh": "Đồng Tháp",
//                 "ten_quan": null,
//                 "thang_kehoach": "      34,686.54",
//                 "thang_luyke_thuchien": "      28,885.28",
//                 "thang_phantram_th": "          83.28",
//                 "quy_kehoach": "     102,837.89",
//                 "quy_luyke_thuchien": "      28,885.28",
//                 "quy_phantram_th": "          28.09",
//                 "nam_kehoach": "     413,863.65",
//                 "nam_luyke_thuchien": "     132,853.37",
//                 "nam_phantram_th": "          32.10",
//                 "tb_thang_hientai": "         962.85",
//                 "tb_thang_truoc": "       1,116.95",
//                 "ss_bq_tocdo_tang": "         -13.80",
//                 "tb_thang_hientai_1": "         962.85",
//                 "tb_ngay_cungky": "       1,116.95",
//                 "ss_bq_tocdo_tang_ngaycungky": "         -13.80",
//                 "tb_thang_hientai_2": "         962.85",
//                 "tb_thang_cungky": "       1,073.04",
//                 "ss_bq_tocdo_tang_thangcungky": "         -10.27",
//                 "tb_lk_ngay_nam_n": "       1,097.96",
//                 "tb_lk_ngay_nam_n_1": "         855.66",
//                 "ss_bq_tdt_lkengay_2nam": "          28.32",
//                 "tb_ngay_nam_n": "       1,097.96",
//                 "tb_ngay_nam_n_1": "       1,060.57",
//                 "ss_bq_tdt_2nam": "           3.53",
//                 "d1": 28885,
//                 "d2": 0,
//                 "d3": 0,
//                 "d4": 0,
//                 "d5": 0,
//                 "d6": 0,
//                 "d7": 0,
//                 "d8": 0,
//                 "d9": 0,
//                 "d10": 0,
//                 "d11": 0,
//                 "d12": 0,
//                 "d13": 0,
//                 "d14": 0,
//                 "d15": 0,
//                 "d16": 0,
//                 "d17": 0,
//                 "d18": 0,
//                 "d19": 0,
//                 "d20": 0,
//                 "d21": 0,
//                 "d22": 0,
//                 "d23": 0,
//                 "d24": 0,
//                 "d25": 0,
//                 "d26": 0,
//                 "d27": 0,
//                 "d28": 0,
//                 "d29": 0,
//                 "d30": 0,
//                 "d31": 0
//             },
//             {
//                 "nam": 2020,
//                 "thang": 4,
//                 "id_tinh": null,
//                 "ten_tinh": "Trung tam",
//                 "ten_quan": null,
//                 "thang_kehoach": "     238,420.42",
//                 "thang_luyke_thuchien": "     194,663.98",
//                 "thang_phantram_th": "          81.65",
//                 "quy_kehoach": "     706,863.60",
//                 "quy_luyke_thuchien": "     194,663.98",
//                 "quy_phantram_th": "          27.54",
//                 "nam_kehoach": "   2,841,965.92",
//                 "nam_luyke_thuchien": "     905,253.39",
//                 "nam_phantram_th": "          31.85",
//                 "tb_thang_hientai": "       6,488.84",
//                 "tb_thang_truoc": "       7,635.84",
//                 "ss_bq_tocdo_tang": "         -15.02",
//                 "tb_thang_hientai_1": "       6,488.84",
//                 "tb_ngay_cungky": "       7,635.84",
//                 "ss_bq_tocdo_tang_ngaycungky": "         -15.02",
//                 "tb_thang_hientai_2": "       6,488.84",
//                 "tb_thang_cungky": "       7,376.93",
//                 "ss_bq_tocdo_tang_thangcungky": "         -12.04",
//                 "tb_lk_ngay_nam_n": "       7,481.45",
//                 "tb_lk_ngay_nam_n_1": "       5,775.07",
//                 "ss_bq_tdt_lkengay_2nam": "          29.55",
//                 "tb_ngay_nam_n": "       7,481.45",
//                 "tb_ngay_nam_n_1": "       7,273.87",
//                 "ss_bq_tdt_2nam": "           2.85",
//                 "d1": 194664,
//                 "d2": 0,
//                 "d3": 0,
//                 "d4": 0,
//                 "d5": 0,
//                 "d6": 0,
//                 "d7": 0,
//                 "d8": 0,
//                 "d9": 0,
//                 "d10": 0,
//                 "d11": 0,
//                 "d12": 0,
//                 "d13": 0,
//                 "d14": 0,
//                 "d15": 0,
//                 "d16": 0,
//                 "d17": 0,
//                 "d18": 0,
//                 "d19": 0,
//                 "d20": 0,
//                 "d21": 0,
//                 "d22": 0,
//                 "d23": 0,
//                 "d24": 0,
//                 "d25": 0,
//                 "d26": 0,
//                 "d27": 0,
//                 "d28": 0,
//                 "d29": 0,
//                 "d30": 0,
//                 "d31": 0
//             }
//         ],
//         "columns": [
//             {
//                 "Header": "Chỉ tiêu",
//                 "fixed": "left",
//                 "columns": [
//                     {
//                         "Header": "Tỉnh",
//                         "accessor": "ten_tinh",
//                         "width": 120
//                     }
//                 ]
//             },
//             {
//                 "Header": "Tháng",
//                 "columns": [
//                     {
//                         "Header": "Tháng",
//                         "accessor": "thang",
//                         "width": 60,
//                         "className": "center"
//                     },
//                     {
//                         "Header": "Năm",
//                         "accessor": "nam",
//                         "width": 60,
//                         "className": "center"
//                     }
//                 ]
//             },
//             {
//                 "Header": "Lũy kế Tháng 4",
//                 "columns": [
//                     {
//                         "Header": "KH",
//                         "accessor": "thang_kehoach",
//                         "width": 100,
//                         "className": "right"
//                     },
//                     {
//                         "Header": "TH",
//                         "accessor": "thang_luyke_thuchien",
//                         "width": 100,
//                         "className": "right"
//                     },
//                     {
//                         "Header": "%TH",
//                         "accessor": "thang_phantram_th",
//                         "width": 100,
//                         "className": "right"
//                     }
//                 ]
//             },
//             {
//                 "Header": "Lũy kế Quý 2/2020",
//                 "columns": [
//                     {
//                         "Header": "KH",
//                         "accessor": "quy_kehoach",
//                         "width": 100,
//                         "className": "right"
//                     },
//                     {
//                         "Header": "TH",
//                         "accessor": "quy_luyke_thuchien",
//                         "width": 100,
//                         "className": "right"
//                     },
//                     {
//                         "Header": "%TH",
//                         "accessor": "quy_phantram_th",
//                         "width": 100,
//                         "className": "right"
//                     }
//                 ]
//             },
//             {
//                 "Header": "Lũy kế Năm 2020",
//                 "columns": [
//                     {
//                         "Header": "KH",
//                         "accessor": "nam_kehoach",
//                         "width": 100,
//                         "className": "right"
//                     },
//                     {
//                         "Header": "TH",
//                         "accessor": "nam_luyke_thuchien",
//                         "width": 100,
//                         "className": "right"
//                     },
//                     {
//                         "Header": "%TH",
//                         "accessor": "nam_phantram_th",
//                         "width": 100,
//                         "className": "right"
//                     }
//                 ]
//             },
//             {
//                 "Header": "So sánh bình quân với tháng trước",
//                 "columns": [
//                     {
//                         "Header": "Tháng 4",
//                         "accessor": "tb_thang_hientai",
//                         "width": 100,
//                         "className": "right"
//                     },
//                     {
//                         "Header": "Tháng 3",
//                         "accessor": "tb_thang_truoc",
//                         "width": 100,
//                         "className": "right"
//                     },
//                     {
//                         "Header": "Tốc độ tăng (%)",
//                         "accessor": "ss_bq_tocdo_tang",
//                         "width": 130,
//                         "className": "right"
//                     }
//                 ]
//             },
//             {
//                 "Header": "So sánh bình quân ngày",
//                 "columns": [
//                     {
//                         "Header": "Tháng 4",
//                         "accessor": "tb_thang_hientai_1",
//                         "width": 100,
//                         "className": "right"
//                     },
//                     {
//                         "Header": "Tháng 3",
//                         "accessor": "tb_ngay_cungky",
//                         "width": 100,
//                         "className": "right"
//                     },
//                     {
//                         "Header": "Tốc độ tăng (%)",
//                         "accessor": "ss_bq_tocdo_tang_ngaycungky",
//                         "width": 130,
//                         "className": "right"
//                     }
//                 ]
//             },
//             {
//                 "Header": "So sánh bình quân tháng",
//                 "columns": [
//                     {
//                         "Header": "Năm 2020",
//                         "accessor": "tb_thang_hientai_2",
//                         "width": 100,
//                         "className": "right"
//                     },
//                     {
//                         "Header": "Năm 2019",
//                         "accessor": "tb_thang_cungky",
//                         "width": 100,
//                         "className": "right"
//                     },
//                     {
//                         "Header": "Tốc độ tăng (%)",
//                         "accessor": "ss_bq_tocdo_tang_thangcungky",
//                         "width": 130,
//                         "className": "right"
//                     }
//                 ]
//             },
//             {
//                 "Header": "So sánh bình quân lũy kế ngày",
//                 "columns": [
//                     {
//                         "Header": "Năm 2020",
//                         "accessor": "tb_lk_ngay_nam_n",
//                         "width": 130,
//                         "className": "right"
//                     },
//                     {
//                         "Header": "Năm 2019",
//                         "accessor": "tb_lk_ngay_nam_n_1",
//                         "width": 130,
//                         "className": "right"
//                     },
//                     {
//                         "Header": "Tốc độ tăng (%)",
//                         "accessor": "ss_bq_tdt_lkengay_2nam",
//                         "width": 130,
//                         "className": "right"
//                     }
//                 ]
//             },
//             {
//                 "Header": "So sánh bình quân năm",
//                 "columns": [
//                     {
//                         "Header": "Năm 2020",
//                         "accessor": "tb_ngay_nam_n",
//                         "width": 100,
//                         "className": "right"
//                     },
//                     {
//                         "Header": "Năm 2019",
//                         "accessor": "tb_ngay_nam_n_1",
//                         "width": 100,
//                         "className": "right"
//                     },
//                     {
//                         "Header": "Tốc độ tăng (%)",
//                         "accessor": "ss_bq_tdt_2nam",
//                         "width": 130,
//                         "className": "right"
//                     }
//                 ]
//             },
//             {
//                 "Header": "Ngày",
//                 "columns": [
//                     {
//                         "Header": "1",
//                         "accessor": "d1",
//                         "width": 40,
//                         "className": "right"
//                     },
//                     {
//                         "Header": "2",
//                         "accessor": "d2",
//                         "width": 40,
//                         "className": "right"
//                     },
//                     {
//                         "Header": "3",
//                         "accessor": "d3",
//                         "width": 40,
//                         "className": "right"
//                     },
//                     {
//                         "Header": "4",
//                         "accessor": "d4",
//                         "width": 40,
//                         "className": "right"
//                     },
//                     {
//                         "Header": "5",
//                         "accessor": "d5",
//                         "width": 40,
//                         "className": "right"
//                     },
//                     {
//                         "Header": "6",
//                         "accessor": "d6",
//                         "width": 40,
//                         "className": "right"
//                     },
//                     {
//                         "Header": "7",
//                         "accessor": "d7",
//                         "width": 40,
//                         "className": "right"
//                     },
//                     {
//                         "Header": "8",
//                         "accessor": "d8",
//                         "width": 40,
//                         "className": "right"
//                     },
//                     {
//                         "Header": "9",
//                         "accessor": "d9",
//                         "width": 40,
//                         "className": "right"
//                     },
//                     {
//                         "Header": "10",
//                         "accessor": "d10",
//                         "width": 40,
//                         "className": "right"
//                     },
//                     {
//                         "Header": "11",
//                         "accessor": "d11",
//                         "width": 40,
//                         "className": "right"
//                     },
//                     {
//                         "Header": "12",
//                         "accessor": "d12",
//                         "width": 40,
//                         "className": "right"
//                     },
//                     {
//                         "Header": "13",
//                         "accessor": "d13",
//                         "width": 40,
//                         "className": "right"
//                     },
//                     {
//                         "Header": "14",
//                         "accessor": "d14",
//                         "width": 40,
//                         "className": "right"
//                     },
//                     {
//                         "Header": "15",
//                         "accessor": "d15",
//                         "width": 40,
//                         "className": "right"
//                     },
//                     {
//                         "Header": "16",
//                         "accessor": "d16",
//                         "width": 40,
//                         "className": "right"
//                     },
//                     {
//                         "Header": "17",
//                         "accessor": "d17",
//                         "width": 40,
//                         "className": "right"
//                     },
//                     {
//                         "Header": "18",
//                         "accessor": "d18",
//                         "width": 40,
//                         "className": "right"
//                     },
//                     {
//                         "Header": "19",
//                         "accessor": "d19",
//                         "width": 40,
//                         "className": "right"
//                     },
//                     {
//                         "Header": "20",
//                         "accessor": "d20",
//                         "width": 40,
//                         "className": "right"
//                     },
//                     {
//                         "Header": "21",
//                         "accessor": "d21",
//                         "width": 40,
//                         "className": "right"
//                     },
//                     {
//                         "Header": "22",
//                         "accessor": "d22",
//                         "width": 40,
//                         "className": "right"
//                     },
//                     {
//                         "Header": "23",
//                         "accessor": "d23",
//                         "width": 40,
//                         "className": "right"
//                     },
//                     {
//                         "Header": "24",
//                         "accessor": "d24",
//                         "width": 40,
//                         "className": "right"
//                     },
//                     {
//                         "Header": "25",
//                         "accessor": "d25",
//                         "width": 40,
//                         "className": "right"
//                     },
//                     {
//                         "Header": "26",
//                         "accessor": "d26",
//                         "width": 40,
//                         "className": "right"
//                     },
//                     {
//                         "Header": "27",
//                         "accessor": "d27",
//                         "width": 40,
//                         "className": "right"
//                     },
//                     {
//                         "Header": "28",
//                         "accessor": "d28",
//                         "width": 40,
//                         "className": "right"
//                     },
//                     {
//                         "Header": "29",
//                         "accessor": "d29",
//                         "width": 40,
//                         "className": "right"
//                     },
//                     {
//                         "Header": "30",
//                         "accessor": "d30",
//                         "width": 40,
//                         "className": "right"
//                     },
//                     {
//                         "Header": "31",
//                         "accessor": "d31",
//                         "width": 40,
//                         "className": "right"
//                     }
//                 ]
//             }
//         ]
//     }
// };
// var dataToTable = dataJson['data'];
// // console.log(dataToTable['data']);
// function buildTable(data){
//     var tem_h = document.getElementById('temp_head');
//     var tem_b = document.getElementById('tem_body');
// 	for(var i = 0 ; i< data['columns'].length ; i++){
// 			var row = `
// 							<td scope="col"  class="table-primary" colspan='${data['columns'][i]['columns'].length} ' style="text-align:center">${data['columns'][i]['Header']}</td>			
// 					  `;
// 			tem_h.innerHTML += row;
//         for(var j= 0 ;j< data['columns'][i]['columns'].length; j++){
//             var row_collect = `
// 							<td scope="col" class="table-secondary" style="text-align:center">${data['columns'][i]['columns'][j]['Header']}</td>			
// 					  `;
//             tem_b.innerHTML += row_collect;
//         }
//     }       
//     //Content-table
//     var tem_c = document.getElementById('temp_content');
//     for(var i = 0 ; i< data['data'].length ; i++){ 
//         var id_temp  = 'row_';
//         id_temp = id_temp + i;
//         tem_c.innerHTML += "<tr id="+`${id_temp}`+"></tr>";
//         var tem_contnet = document.getElementById(`${id_temp}`);
//         var swap_position = data['data'][i].ten_tinh
//         data['data'][i].ten_tinh = data['data'][i].nam;
//         data['data'][i].nam = swap_position;
//       for(var con_content in data['data'][i]){
//         if(con_content != 'id_tinh'){
//             if(data['data'][i][con_content] != null){
//                 var content_row =`<td scope="col">${data['data'][i][con_content]}</td>`;
//                 tem_contnet.innerHTML += content_row;  
//             } 
//         }
//     }
      
//     }  
// }
// buildTable(dataToTable);
